version: '3.3'
services:
  db:
    image: postgres:14.15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demo
  aws:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-1
      - SERVICES=s3,sqs,sns
    volumes:
      - ./tmp/localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.120.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
volumes:
  postgres-data: